services:
  web:
    build:
      context: .
      dockerfile: Dockerfile 
      args:
        # Pass all build-time public environment variables here
        - NEXT_PUBLIC_SUPABASE_URL=https://mjrdngowtmhzybzrrfjy.supabase.co
        - NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=sb_publishable_WwBP0_fqHU2ckfIK8gZT9w_A1XuFZZb
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env.local
    restart: always